### ISSUE TITLE
PCLCrypto version

### ISSUE THREAD

**Issue by leastprivilege** [dvsekhvalnov/jose-rt#1]
Hi, 

have you ever considered creating a version of Jose using PCLCrypto - having a portable implementation (maybe with less features) would be much more useful than a RT version.

This way we could have a compact JWT lib for desktop, RT, Phone, UWP and Xamarin..

**Comment by dvsekhvalnov** [comment]
Hi @leastprivilege ,

i've never heard about PCLCrypto before :)  It may be interesting idea to explore. But right now priority is to make github.com/dvsekhvalnov/jose-jwt netcore compatible.

There is also one thing with libraries implementing crypto algorithms. Once you start bundling and redistributing them with your app - you becoming subject for cryptography export regulations. Which may (or may not) be an issue for somebody. So far all JOSE spec implementations i did relies only on standard library (zero-dependency) and therefore do not imply any distribution restrictions. That was original design goal. I'm fine to reconsider this approach if there are demand/interest in more portable implementations and the goal worse it.

**Comment by leastprivilege** [comment]
PCLCrypto is not a crypo implementation - but simply an abstraction and common API (modeled after the WinRT crypto API) that forwards to the corresponding native platform implementation. Since .NET Core can consume PCL - this would have even broader reach than a Core lib on its own.

It is maintained by a MS guy

https://github.com/AArnott/PCLCrypto/wiki/Algorithms-X-platforms-support

**Comment by dvsekhvalnov** [comment]
Ok, thanks for info. Wrapper sounds more interesting. I don't have any free time for it right now but will try to take a look after netcore stuff.  

Also would be interesting to get some plans from PCLCrypto maintainer, at first glance it have gaps with covering AES-GCM and elliptic curve support at the moment.

**Comment by leastprivilege** [comment]
Well - the thing is - what's really needed right now is a x-plat JWT lib that supports HS256 and RS256 signing. Nothing like that exists - you would solve a real problem with that (much realer than a .net core impl). 

That would be easy to do.

**Comment by dvsekhvalnov** [comment]
Ok, you almost convinced me. I'll try to find some time and add some experimental library version :)

**Comment by leastprivilege** [comment]
I am working on a xplat OpenID Connect library for native mobile clients. Right now we use an endpoint in the STS to validate the id token (jwt). A xplat jwt lib is a blocker for that kind of work right now.

Let me know when you want me to try whatever you have - as I said that would solve a real world problem (and there is no other option around).

**Comment by dvsekhvalnov** [comment]
ok, sounds like a plan.

**Comment by leastprivilege** [comment]
Hey, 

we had a look at our requirements - just to confirm JSON + JWT signing with RS256 and HS256 would be all we need.

**Comment by dvsekhvalnov** [comment]
@leastprivilege , just to clarify:

you are looking to portable class library (windows runtime component?) target to:
- Windows 8
- Windows Phone 8.1
- Silverlight 5
- Windows Phone Silverlight 8

? Or something else?

**Comment by leastprivilege** [comment]
and Xamarin iOS + Android

**Comment by leastprivilege** [comment]
like this project

https://github.com/IdentityModel/IdentityModel.OidcClient/blob/dev/src/IdentityModel.OidcClient/IdentityModel.OidcClient.csproj#L16
https://github.com/IdentityModel/IdentityModel.OidcClient/blob/dev/IdentityModel.OidcClient.nuspec#L23

**Comment by dvsekhvalnov** [comment]
mm.. don't have Xamarin targets in my VS2013.  Do i need newer one? or do i need to additionally download something?

**Comment by leastprivilege** [comment]
I think it is good enough to have this in the csproj

`<TargetFrameworkProfile>Profile111</TargetFrameworkProfile>`

**Comment by leastprivilege** [comment]
sorry - i think it is 

`<TargetFrameworkProfile>Profile259</TargetFrameworkProfile>`

**Comment by leastprivilege** [comment]
it's confusing...

**Comment by leastprivilege** [comment]
see also here

http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY/

**Comment by dvsekhvalnov** [comment]
That page doesn't mention Xamarin at all.  Ok, i'll try to set project with PCLCrypto on my VS2013 and you can try if it is working on Xamarin, then we figure out.

**Comment by leastprivilege** [comment]
Right - it is basically the right combination of platforms that makes it also Xamarin compatible. Cool let me know!

**Comment by leastprivilege** [comment]
Hey, 

did you make any progress?

**Comment by dvsekhvalnov** [comment]
Hi @leastprivilege ,

planning to do some initial work on 9-10 march. I'll post update.

**Comment by dvsekhvalnov** [comment]
@leastprivilege , i set a project here: https://github.com/dvsekhvalnov/jose-pcl

we can move our discussion to the new project.  

In the mean time, what json library are you using for such cross platform things? Json.NET? Working on Xamarin?

**Comment by leastprivilege** [comment]
great!

Json.Net works fine yes

**Comment by dvsekhvalnov** [comment]
@leastprivilege , closing this one and moving conversation to https://github.com/dvsekhvalnov/jose-pcl/issues/1
